### ISSUE TITLE
demo examples clarification

### ISSUE THREAD

**Issue by kevinstan** [JudyYe/CVP#1]
Hi, thank you for your code. I'm wondering what the format of images in `examples/` should be for testing a demo on ShapeStacks. Can you upload a simple example (i.e. remove `examples/` from your `.gitignore`? And what should the contents of `demo_ss.txt` be? 

Thanks,
Kevin

**Comment by whitealex95** [comment]
I too have a question on this issue. Need help...

**Comment by hagg30** [comment]
Also same issues here. Please clarify the format of the textfile demo_ss.txt

**Comment by cuge1995** [comment]
Also same issues here. Please clarify the format of the textfile demo_ss.txt

**Comment by JudyYe** [comment]
Hi, 
I've removed examples/ from .gitignore.
